---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: tools
spec:
  encryptedData:
    .dockerconfigjson: AgCZD5qmo7PHrhtFVqT600eD4yYTr2vWPgd5gbgL1vL5TFt78RZTOKr2hNMYmYJ5UW0EQoSCWcYW2/L2mnFKyIS7TEpLkR7cdMHyUg1ACbTQHXakQGUVSrCD0OGEA8rqtDo2CIdoAEHgSr+D07oLRObX9bd3M08/25Z+hL9nkaZ3483sD+/qnQhoJkeQ6L0gxvPOVxCVFFTesJ1ik6qENCcl+g3lYFMdo090GwQyibyXLbvoX0aF9lf8Sfvg1FURBMEoIaU6MkNQT/vdnuEBbU7Fllk6lUUPw1iX1mNqPpY3YvjPk143axZ/niAKBUIe996svRPBOT2zQauaQbS683flXDTPqIJG2ig4IndTHQELJcP+rm+5nqbb47H5WQ7Gq7ZIbnLFNQrGW3oH4UniLmvBrA61F6a0EHA8h4ukzzL9foL3VrB8ZOGys2b/xH2fWkL257ZDe0G94z+7WLRrbT517D478vex4tIDuw9d8CtAnhbHVkwC7Zw5+xsNB6LCuxfRDObHGRc4dbEJR8gbCiLNHanZnykptdrN9qWDHlXBWTyKWh4dCBKXnaefZ0yPWGJCIxY6ntpx2TyVqOKd2QDy6x/DrIjYa0Cq3XKUIsv7F9452gQuUB3SSSiZBliRBWFzrubZ7orKUVvvBrKQ+Dn7SPnYfXarvbW/f48NeWGdhaLbtMCJkmiUvc08jqAqr490c3sY2w7crO3LL1AXfMHyl1HPnT78NQWOMr5EpgKTHieoRJwlOoWmDbLgnvjBq2aV89YrJsgztTjqoks10ShWyHyZozyzf6I2cwBVqpers3D3d0AMLGdsTIWshXv1l0jHMDWEHaIpnGlglcmUXWdwB4nD80r+C4zlbU8zV7xod3ZOXDfZnZ4n23JpdtziFoyaKdsyqakCP6+i/LJuT/LomYRrJ/EEDHnk2aVHHtEVgqFEkvvc7Px3pbQ0exl3PyO5G8Zm2lZdVEUsBL0zQIYsI822rBGK3Wpejm7Em7iYvDNB5m0KFa967PQk3lJAm7FOKHdEtVW8vaz+/WKP7np4B1d0I437CrJa3RGtNjFj2fWSEav+WntKJCVgRwDUhX7c77w8QE9CVGn6IM/t+HdOWfTQq+s/XTKbFBRHlH7RgJKi/pFPA2XnAw3ApFZYT8F60bjv3/TeoJNAn3W1leZrF6zXtD2F9LCKT+RpzpmMsQKorhmwnuwCbbHiTFUU8xF8sYojZcLa/DFU9mtJaoTTrS52Gujr0xvrHJfsnq27Ciea8FYPkGJqu2U+HQ6/mU0Bd/nbAOwJa+JueVCZzQYOx4kd6bU9IOijZD6d7ibVIkKpeTsZXRLHRtF5EpcecXoH+RZoMXpFiSuR7X10kHMtyJZGauObEFoUVvW8StfBI9qNDkkQ
  template:
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: tools
    type: kubernetes.io/dockerconfigjson
